#!/bin/sh
#
# memo
#
# dp_sendfits.sh
# dp_procstat.pl
#
##########################################################
# IRC scan pipeline (2006/12/10版本体)
#   On-ineモード(DataBaseにアクセスできる環境)を想定
#   上流(取得元)DataBaseは環境変数${IRCSCAN_DB}で設定する
#   下流(登録先)DataBaseは環境変数${IRCSCAN_WDB}で設定する
#
# 起動
# (1)Debugモード
#    Usage: pipeline_v061210.sh prefix ds9_title
#           prefix...ファイル名のprefix。F000010_4NSなど。
#           debug...引数が2つだとdebugモードに入る
# (2)静かに実行モード
#    Usage: pipeline_v0809.sh prefix
#
# 備考
#   (タスクの混在)処理速度節約のため１つコマンドで複数タスクを
#   兼る場合がある。本来は１タスク１モジュールが望ましい。
#
# 天筒メモ
# 1305_oldscatは、diffuse天体から散乱光を差し引く時に使用します。
# satur.dat, cray.datを残します。
# 1412: l1kando -> l1kando1412

##### Variables ##########################################
# nsrc ... Sourceの数
# n_msx ... MSX天体とマッチした数
# n_iras ... IRAS天体とマッチした数
# n_tmass ... 2MASS(bright)天体とマッチした数
# calc ... 1:星のデータを元に位置合せをした 0:できなかった
# xshift ... dRA
# yshift ... dDec

##### Functions ##########################################
# do_check_conf_files() ... 設定ファイルがあるかチェック
#
# do_retrieve_conf_files() ... 設定ファイルを取得する
#  outfile: sep11.sex sep11.parm ...
#
# do_get_rawdata_db(prefix) ... Pipe_lineの入力データをDBからとってくる
#  out: fid ch
#
# do_setup() ... 画面のsetupを行う
# do_adu2es() ... ADU⇒e-の変換を行う
# do_save_cache() ... 変数を保存する(再スタートのため)
# do_rst_slit_msk() ...
# do_linearity() ...
# do_dark_subtract() ...
# do_satmask() ...
# do_diff() ...
# do_sext_scon66() ...
# do_daophot() ...

# forallskyは、remzodがあるやつないやつ、更にnscanも作成。

bin_dir="/usr/mirmap/bin/"

# 変数を保存する
function do_save_vals
{
   export LANG=C; cur_date_str=`date`;
   printf "#-------------------------------------------------------------#\n" > ${prefix}.cache
   echo "# ${prefix}.cache"           >> ${prefix}.cache;
   echo "# Generated by $pipeline"    >> ${prefix}.cache;
   echo "#           at $cur_date_str">> ${prefix}.cache;
   echo "#           by $USER@$HOST"  >> ${prefix}.cache;

   printf "#--- FITS ----------------------------------------------------#\n" >> ${prefix}.cache
   printf "prefix=\"$prefix\" # Prefix (ex) F0000001_4NS\n" >> ${prefix}.cache
   printf "ch=\"$ch\"                # Channel S/L\n" >> ${prefix}.cache
   printf "fid=$fid        # FrameID\n" >> ${prefix}.cache
   printf "dhuti=$dhuti      # 36(64)bit TI \n" >> ${prefix}.cache
   printf "ccsdsti=$ccsdsti     # 32bit TI\n" >> ${prefix}.cache
   printf "datastr=\"$datestr\"  # Date in YYYY-MM-DD format\n" >> ${prefix}.cache
   printf "timestr=\"$timestr\"    # Time in HH:MM:SS format\n" >> ${prefix}.cache
   printf "rstm=\"Long\"           # Reset mode\n" >> ${prefix}.cache
   printf "rstp=\"306\"            # Reset period\n" >> ${prefix}.cache

   printf "#--- Status --------------------------------------------------#\n" >> ${prefix}.cache
   printf "rst1=%-8.1f  # Row#1 reset level (e)\n"      $rst1  >> ${prefix}.cache;
   printf "nrst1=%-8.1f # Row#1 noise of reset (e)\n"   $nrst1 >> ${prefix}.cache;
   printf "rst2=%-8.1f  # Row#2 reset level (e)\n"      $rst2  >> ${prefix}.cache;
   printf "nrst2=%-8.1f # Row#2 noise of reset (e)\n"   $nrst2 >> ${prefix}.cache;
   printf "bg1=%-8.3f   # Row#1 background level (e)\n" $bg1   >> ${prefix}.cache;
   printf "nbg1=%-8.3f  # Row#1 background noise (e)\n" $nbg1  >> ${prefix}.cache;
   printf "bg2=%-8.3f   # Row#2 background level (e)\n" $bg2   >> ${prefix}.cache;
   printf "nbg2=%-8.3f  # Row#2 background noise (e)\n" $nbg2  >> ${prefix}.cache;
   printf "msk1=%-8.3f  # Row#1 slit-mask level (e)\n"  $msk1  >> ${prefix}.cache;
   printf "nmsk1=%-8.3f # Row#1 slit-mask noise (e)\n"  $nmsk1 >> ${prefix}.cache;
   printf "msk2=%-8.3f  # Row#2 slit-mask level (e)\n"  $msk2  >> ${prefix}.cache;
   printf "nmsk2=%-8.3f # Row#2 slit-mask noise (e)\n"  $nmsk2 >> ${prefix}.cache;

   printf "#--- Status2 --------------------------------------------------#\n" >> ${prefix}.cache
   printf "bgA=%-8.3f # \n"  $bgA >> ${prefix}.cache;
   printf "nbgA=%-8.3f # \n"  $nbgA >> ${prefix}.cache;
   printf "bgB=%-8.3f # \n"  $bgB >> ${prefix}.cache;
   printf "nbgB=%-8.3f # \n"  $nbgB >> ${prefix}.cache;
   printf "bgC=%-8.3f # \n"  $bgC >> ${prefix}.cache;
   printf "nbgC=%-8.3f # \n"  $nbgC >> ${prefix}.cache;
   printf "c1=%-8.3f # \n"  $c1 >> ${prefix}.cache;
   printf "c2=%-8.3f # \n"  $c2 >> ${prefix}.cache;
   printf "c3=%-8.3f # \n"  $c3 >> ${prefix}.cache;
   printf "craA=%-8.3f # \n"  $craA >> ${prefix}.cache;
   printf "cdeA=%-8.3f # \n"  $cdeA >> ${prefix}.cache;
   printf "craB=%-8.3f # \n"  $craB >> ${prefix}.cache;
   printf "cdeB=%-8.3f # \n"  $cdeB >> ${prefix}.cache;
   printf "craC=%-8.3f # \n"  $craC >> ${prefix}.cache;
   printf "cdeC=%-8.3f # \n"  $cdeC >> ${prefix}.cache;

   printf "#--- Events --------------------------------------------------#\n" >> ${prefix}.cache;
   printf "nsrc=%-4d      # Num of seconds confirmed events (Source)\n" $nsrc  >> ${prefix}.cache;
   printf "nrej1=%-4d     # Row#1 num of rejected events (Glitch)\n"    $nrej1 >> ${prefix}.cache;
   printf "nrej2=%-4d     # Row#2 num of rejected events (Glitch)\n"    $nrej2 >> ${prefix}.cache;

   printf "#--- WCS -----------------------------------------------------#\n" >> ${prefix}.cache;
   printf "cra=$cra   # ra  in J2000 decimal\n"  >> ${prefix}.cache;
   printf "cde=$cde   # dec in J2000 decimal\n"  >> ${prefix}.cache;
   printf "xshift=%-16.9f   # dRA correction\n" $xshift >> ${prefix}.cache;
   printf "yshift=%-16.9f   # dDec correction\n" $yshift >> ${prefix}.cache;
   printf "n_msx=%-4d     # Num of MSX cross-ID\n" $n_msx >> ${prefix}.cache;
   printf "n_iras=%-4d    # Num of IRAS cross-ID\n" $n_iras >> ${prefix}.cache;
   printf "n_tmass=%-4d   # Num of 2MASS(<8mag) cross-ID\n" $n_tmass >> ${prefix}.cache;
   printf "calc=%-2d       # 1:Local P.R. done   0:Not done\n" $calc >> ${prefix}.cache;
   printf "#-------------------------------------------------------------#\n" >> ${prefix}.cache;
}

function initialize_params
{
   #--- FITS定義関連 -----------------------------------------#
    prefix="F000000001_4NS" # ファイルのPrefix。(例) F0000001_4NS
    ch="S"                  # Channel S/L
    fid=0                   # FrameID
    dhuti=0                 # 36(64)bit TI 
    ccsdsti=0               # 32bit TI
    datastr="2006-02-22"    # 日時 2006-02-22 形式
    timestr="06:22:00"      # 時刻 06:22:00 形式
    rstm="Long"             # Reset mode - Script中埋め込みであるが、本来は変数
    rstp="306"              # Reset period - Script中埋め込みであるが、本来は変数
   #--- Status関連 -------------------------------------------#
    rst1=0     # 1行目のResetレベル
    nrst1=0    # 1行目のResetのNoise
    rst2=0     # 2行目のResetレベル
    nrst2=0    # 2行目のResetのNoise
    bg1=0
    nbg1=0
    bg2=0
    nbg2=0
    msk1=0
    nmsk1=0
    msk2=0
    nmsk2=0
   #--- Status2関連
   bgA=0
   nbgA=0
   bgB=0
   nbgB=0
   bgC=0
   nbgC=0
   c1=0
   c2=0
   c3=0
   craA=0
   cdeA=0
   craB=0
   cdeB=0
   craC=0
   cdeC=0
   #--- Event関連 --------------------------------------------#
    nsrc=0     # Seconds confiramされたイベント(天体)数
    nrej1=0    # 1行目のeventで除外された数(放射線)
    nrej2=0    # 2行目のeventで除外された数(放射線)
   #--- WCS関連 ----------------------------------------------#
    coords="0.0 0.0"  # 10進で "ra dec"
    cra=0.0;
    cde=0.0;
    xshift=0   # RA方向のshift量
    yshift=0   # Dec方向のshift量
    n_msx=0    # MSX天体とmatchした数
    n_iras=0   # IRAS天体とmatchした数
    n_tmass=0  # 2MASS(<8mag)天体とmatchした数
    calc=0     # 1:天体による位置合せ有 0:無理
   #----------------------------------------------------------#
   # FITS checkerを入れる
}

function debug_stdout
{
    if [ $debug -eq 1 ]; then
	clear;
	do_save_vals;            # 変数を保存
	cat ${prefix}.cache;     # 変数を表示
	/bin/ls -lt ${prefix}*;  # 中間ファイルを新しい順に表示
	echo -n ">";             # Returnが押されるのを待つ
	read;
    fi
}

function debug_load
{
    if [ -f ${prefix}.cache ]; then
	. ${prefix}.cache
    else
	echo "Fatal in debug_load(): ${prefix}.cache not found." 1>&2;
	exit -1;
    fi
}

# 設定ファイル等があるかチェックする
function do_check_conf_files
{
    for i in sep11S.sex sep11S.param mix66S.sex mix66S.param \
	ds9.grd default.nnw mskS66.fits mskL66.fits S.swarp L.swarp
    do
      if [ -f $i ]; then
	  echo -n "";
      else
	  cp -rf ${cal_dir}/$i .
	  # exit -1;
      fi
    done

    if [ ! -f login.cl ]; then
	#mkiraf作成 本当はirafのバージョンで分けるべき 2.16より前は前者？
	if [ $(hostname) = "capybara.u.phys.nagoya-u.ac.jp" ];then
	    echo <<EOF | mkiraf
dt100
EOF
	else
	    mkiraf --term=dt100
	fi
    fi
    debug_stdout
}

# 設定ファイル等を取得する
function do_retrieve_conf_files
{
    echo "Retrieving configuration files" 1>&2 ;
    for i in sep11S.sex sep11S.param mix66S.sex mix66S.param \
	ds9.grd default.nnw mskS66.fits mskL66.fits S.swarp L.swarp
    do
      cp ${cal_dir}/$i .
    done
}

# Pipe-lineの入力データをdbからとってくる
function do_get_rawdata_db
{
    prefix=$1;

    # 前ver.との互換性のため文字列分解
    #  prefix=F00XXXX_4NS => fid=XXXX、ch=S
    fid=${prefix#F}; fid=${fid%_4NS}; fid=${fid%_4NL};
    ch=${prefix#F${fid}}; ch=${ch#_4N};
    
    dbget_rawfits3.pl $fid 4N $ch;
    if [ -f ${prefix}.fits ]; then
	echo -n "";
    else
	echo "ERR: ${prefix} not found in DB";
	exit -1;
    fi
}

# 画面のsetupを行う
function do_setup
{
    preifx=$1;
}

# ADU→e変換、double化、Resetレベルのチェック
# dhuti ccsdsti ch datestr timestr rst1 nrst1 rst2 nrst2 も取得
function do_adu2es
{
    prefix=$1;
    
    # ファイルがあることを確認
    if [ -f ${prefix}.fits ]; then echo -n "";
    else echo "Fatal at do_adu2es(): ${prefix}.fits not found" 1>&2; exit -1; fi

    # ADU→e変換する。ついでにHeaderから変数取得。
    str=(`sp2_adu2es ${prefix}.fits ${prefix}.fits`);

      dhuti=${str[0]};
    ccsdsti=${str[1]};
         ch=${str[2]};
    datestr=${str[3]};
    timestr=${str[4]};

       itg1=${str[5]};
      nitg1=${str[6]};
       itg2=${str[7]};
      nitg2=${str[8]};

       rst1=${str[9]};
      nrst1=${str[10]};
       rst2=${str[11]};
      nrst2=${str[12]};

      nzero=${str[9]};

    # 0 level の pixelが10以上あったらFITSが壊れている恐れがある
    if [ $nzero -gt 10 ];then
	echo "Fatal: nzero=$nzero for ${prefix}: please check";
	exit -1;
    fi
}

# 変数をcacheに保存する
# Scriptを部分的にcut&pasteで実行する時は、cacheから変数を読み込む
function do_save_cache
{
cat <<EOF > cache
debug=${debug};
title=$title;
src_dir=${src_dir}; # Source data directory (read only)
cal_dir=${cal_dir}; # Config. files directory (read only)
cmd_dir=${cmd_dir}; # Command directory (read only)
ccsdsti=${ccsdsti}; # CCSDS_TI for FILE ID
PATH=${PATH}
EOF
}

# Reset mask と Slit mask を作る
function do_rst_slit_msk
{
    sp2_rstmsk.pl ${ccsdsti} ${ch} ${rstm} ${rstp} > ${prefix}_slitm.dat;
}

# Non-linearity補正
function do_linearity
{
#sp2_linear2 ${prefix}.fits ${prefix}.fits ${prefix}_linerr.fits ${ch}
# 2008/1/7 SlowScanで使用しているlinearityの式に変更
# sp2_linear3 ${prefix}.fits ${prefix}.fits ${prefix}_linerr.fits ${ch}

sp2_linear140203 ${prefix}.fits ${prefix}.fits ${prefix}_linerr.fits ${ch}
#         080530 -> 140203
}

function do_dark_subtract
{
    echo -n "";
}

function do_satmask
{
    #sp2_saturate ${prefix}.fits ${ccsdsti} 280000 > ${prefix}_sat.dat
    #sp2_saturate ${prefix}.fits $ccsdsti 960000 > ${prefix}_satur.dat
    # 40% linearity
    sp2_saturate ${prefix}.fits $ccsdsti 800000 > ${prefix}_satur.dat
# 2^16*6=393216
# 1pix= 40000 ADUを仮定
}

# 画像の差分、backgroundとslit maskのレベルチェック
#  兼 bg1,nbg1, bg2,nbg2, msk1,nmsk1, msk2,nmsk2 も取得
function do_diff
{
    prefix=$1;

    cp ${prefix}.fits ${prefix}_intg.fits
    str=(`sp2_reed ${prefix}.fits ${prefix}.fits simple`);
      bg1=${str[0]};
     nbg1=${str[1]};
      bg2=${str[2]};
     nbg2=${str[3]};
     msk1=${str[4]};
    nmsk1=${str[5]};
     msk2=${str[6]};
    nmsk2=${str[7]};
}

function do_flat
{
    #sp2_flat_1305 ${prefix}.fits ${prefix}.fits 端がよろしくない
    sp2_flat ${prefix}.fits ${prefix}.fits
}

function do_kando_hosei
{
    #物理的原因がよく分かっていない感度補正(天筒)
    
    ####  月を見た後の感度補正  ####
    #リストからパラメータ抜き出し
    search_ccsdsti=$ccsdsti
    if [ $search_ccsdsti -lt 1000000000 ] ; then
	search_ccsdsti=" "$ccsdsti
    fi
    smoon_listfile=${bin_dir}"smoon_list2"
    if [ -f smoon_list2_mini ] ; then
	smoon_listfile=smoon_list2_mini
    fi

    smoon_data=$(grep -m1 ^"$search_ccsdsti" $smoon_listfile)
    if [ "${smoon_data}" = "" ]; then
	smoon_listfile=${bin_dir}"smoon_list2"
	smoon_data=$(grep -m1 ^"$search_ccsdsti" $smoon_listfile)
    fi
    smoon=$(echo $smoon_data|cut -d ',' -f 2)
    minute_aftermoon=$(echo $smoon_data|cut -d ',' -f 3)

    #パラメータで補正が必要か判断
    do_smoon_correct=0
    do_smoon_correct=$(echo "( $smoon * $smoon < 100 ) && ( $minute_aftermoon < 204)"|bc)
    if [ $do_smoon_correct -eq 1 ] ; then
	smoon_coef_listfile=${bin_dir}"smoon_coeff_"${ch}"_2.list"
	sp2_aftermoon ${prefix}.fits $smoon $minute_aftermoon $smoon_coef_listfile ${prefix}.fits
    fi

    ####  Lの感度が時間変化しているのを補正  ####
    if [ "$ch" = "L" ] ; then
	iyear=$(echo $datestr|cut -c 1-4)
	imonth=$(echo $datestr|cut -c 6-7)
	iday=$(echo $datestr|cut -c 9-10)
	ihour=$(echo $timestr|cut -c 1-2)
	year=$(echo "scale=3; ($imonth -1.) / 12.+($iday -1. +$ihour /24.) /365.+$iyear"|bc)
	sp2_l1kando_1412 ${prefix}.fits $year ${prefix}.fits
	# year=$(echo "scale=3;$imonth / 12.+($iday+$ihour /24.) /365.+$iyear"|bc)
	# sp2_l1kando ${prefix}.fits $year ${bin_dir}year_and_relstr_L.txt ${prefix}.fits
    fi
}

function do_sext_scon66
{
    # 2行別々にSource Extractionを行う
    sex -c sep11S.sex ${prefix}.fits >& /dev/null
    cp test1.cat ${prefix}_sep.cat

    # Background(Source抜き)強度を取得
    str=(`sp2_d2f ${prefix}.fits check_sep.fits ${prefix}_bg.fits`);
      bg1=${str[0]};
     nbg1=${str[1]};
      bg2=${str[2]};
     nbg2=${str[3]};
      bgA=${str[4]};
     nbgA=${str[5]};
      bgB=${str[6]};
     nbgB=${str[7]};
      bgC=${str[8]};
     nbgC=${str[9]};

     # Stray light 開発用 routine
#     q_list_stat ${prefix}_bg.fits 1 4-60 200:300 1 | awk '{print $2,$5}' > l
#     str=(`sh sp2_fit.sh`);
#     c1=${str[0]};
#     c2=${str[1]};
#     c3=${str[2]};

    # SatTrail中にいる天体は除外
    sp2_satrej.pl ${prefix}_sep.cat ${prefix}_satur.dat  ${prefix}_sep.cat

    # HKをHeaderに入れる
    pr2_fitshd080933 ${prefix}.fits ${prefix}.fits > ${prefix}.pos 2> /dev/null

    # 6x6FITSに合成する
    #1305:flatのウェイトを追加 BADPIXELが補正されます
    sp2_comb33 ${prefix}.fits ${prefix}_mix.fits 6
    cp ${prefix}_mix.fits nokosu.fits ###

    # 6x6合成FITSからSource Extractionを行う
    sex -c mix66S.sex ${prefix}_mix.fits >& /dev/null
    cp test1.cat ${prefix}_mix.cat

    # Seconds confirmation
    #str=(`sp2_scon_6to1B.pl ${prefix}_mix.cat ${prefix}_sep.cat ${prefix}_scon.cat ${prefix}_rej1.cat ${prefix}_rej2.cat $ch $dhuti $ccsdsti`);
    str=(`sp2_scon_6to1C.pl ${prefix}_mix.cat ${prefix}_sep.cat ${prefix}_scon.cat ${prefix}_rej1.cat ${prefix}_rej2.cat $ch $dhuti $ccsdsti`);
     nsrc=${str[0]};  # Seconds confirmed 天体の数
    nrej1=${str[1]};  # Rejectされたrow#1のイベントの数
    nrej2=${str[2]};  # Rejectされたrow#2のイベントの数
    nbright=${str[3]};# Bright Sourceの数。

    # カメラ内Stray light 除去:背景
    case "$ch" in
	L)
	    sp2_subscat080930 ${prefix}.fits $bg1 ${prefix}.fits
	    #眩しい光源一覧を見る
	    if [ -f BrightPrefix.list ]; then
		nbright_listed=$(grep -s $prefix "BrightPrefix.list"|wc -l)
		nbright=$(echo "$nbright + $nbright_listed"|bc)

		#カメラ内Stray light 除去:点源
		if [ $nbright -gt 0 ];
		    then
		    cat <<EOF|idl -queue
.com /usr/mirmap/bin/diffusescat/diffuse_remscat
.com /usr/mirmap/bin/PSF_FITTER/diffuse_psf_fitter
.com /usr/mirmap/bin/PSF_FITTER/diffuse_psf_cs
diffuse_remscat,'${prefix}.fits',BRIGHT_LIST="BrightPrefix.list"
exit
EOF
		fi
	    fi
	;;
	*)
	    echo -n "";
	;;
    esac

    sp3_cray2msk.pl cray > ${prefix}_cray.dat

    # Rejectされたeventを塗り潰して、FITSを作り直す
    sp2_comb33_c ${prefix}.fits ${prefix}_mix.fits 6 cray
    #sp2_comb33_1305がフラットのウェイト適用
    
    # 受かった時の積分値情報を追加 (12/28 NEW! 要注意)
    sp2_scon_intg.pl ${prefix}_scon.cat ${prefix}_scon.cat

    debug_stdout
}

# DAO PHOT を使う
function do_daophot
{
    sp_scon2mixcoo.pl ${prefix}_scon.cat >coo
    daowrap.sh ${prefix}_mix.fits coo
    sp_magread.pl mag.mag > ${prefix}_mix.mag
}

# FITSにWCSをつける
function do_wcs
{
    # sp2_xy2wcs080611 ${prefix}_mix.fits ${prefix}_scon.cat 1>${prefix}_wcs.dat 2>${prefix}.pos
    sp2_xy2wcs080931 ${prefix}_mix.fits ${prefix}_scon.cat 1>${prefix}_wcs.dat 2>${prefix}.pos

    # ${prefix}.pos(ピクセル-座標関係の照合ファイル)を元に
    # ${prefix}_mix.fits(6x6合成FITS)に座標をつける
    cp ${prefix}_mix.fits ${prefix}_mixw.fits

    cat <<EOF | cl 1>/dev/null
imstat ${prefix}_mixw.fits
ccmap ${prefix}.pos ${prefix}.out result=STDOUT image=${prefix}_mixw.fits xcol=1 ycol=2 lngcol=3 latcol=4 lngunits="degree" latunits="degree" inter-
ccsetwcs ${prefix}_mixw.fits ${prefix}.out ${prefix}_mixw.fits
logout
EOF
    # (旧版)
    # imwcs -p 1.56 -n 4 -r 0 -u ${prefix}.pos -w ${prefix}_mix.fits 2> /dev/null 1> /dev/null
    # imwcs -v -n 0 -u ${prefix}.pos -w ${prefix}_mix.fits
    # imwcs -n 4 -r 0 -u ${prefix}.pos -w ${prefix}_mix.fits 

    . ./pts3.cmd
    # FITSの中心座標を得る
    #coords=(`xy2sky -jd ${prefix}_mixw.fits 192 925 | awk '{print $1,$2}'`);
    #cra=${coords[0]};
    #cde=${coords[1]};

    # FITSの3点を求める
    #coords=(`xy2sky -jd ${prefix}_mixw.fits 192 308 | awk '{print $1,$2}'`);
    #craA=${coords[0]};
    #cdeA=${coords[1]};
    #
    #craB=$cra;
    #craB=$cde;
    #
    #coords=(`xy2sky -jd ${prefix}_mixw.fits 192 1540 | awk '{print $1,$2}'`);
    #craC=${coords[0]};
    #cdeC=${coords[1]};
    
    # 参照カタログを検索する (廃止)
    # dp_lcat3.pl $cra $cde ${prefix} 2> /dev/null;
    # MSX/2MASS/IRASソースを使って位置を微調整する (廃止)
    # POSファイルをずらし⇒FITSに修正後座標をつける (廃止)
    # wcs.refの内容をscon.catに統合する (廃止)

    #       1     2      3       4        5     6       7      
    echo "$ch $ccsdsti $datestr $timestr # $nsrc $nrej1 $nrej2 $n_tmass $calc $xshift $yshift";
    sp2_catmerge3.pl ${prefix}_scon.cat ${prefix}_wcs.dat $ch $dhuti $ccsdsti ${prefix}_scon.cat
}

##### Main ###########################################################
export PATH=${PATH}:/usr/ircscan/bin
export LD_LIBRARY_PATY=${LD_LIBRARY_PATH}:/usr/local/lib:/usr/ircscan/lib:/usr/mirmap/lib

initialize_params;          # 初期化

# 引数2つならdebug、引数1つなら静かに実行
if   [ $# -eq 2 ]; then  prefix=$1; debug=1; title=$2;     
elif [ $# -eq 1 ]; then  prefix=$1; debug=0; title="NONE"; 
else  echo "Usage: $0 prefix debug title" 1>&2 ; exit -1;
fi

### 準備 #############################################################
pipeline=$0;
cal_dir=/home/ircscan/akari/config;     # 設定ファイル等があるディレクトリ(read only)
export PATH=/usr/ircscan/bin:${PATH}
# do_retrieve_conf_files    # 設定ファイル等を取得
do_check_conf_files         # 設定ファイルが足りているかチェック

do_get_rawdata_db $prefix   # 入力FITSをとってくる

### プロセス #########################################################
do_setup  $prefix           # 画面のsetup
do_adu2es $prefix           # ADU→e/s変換 兼 パラメータ取得
do_rst_slit_msk             # ResetマスクとSlitマスクの作成
do_satmask                  # 飽和のマスク
#exit
itg1=0;itg2=0;
dbget_itg.pl ${ccsdsti} ${ch}
if [ -f itg.cmd ]; then
    . ./itg.cmd
fi
#echo "INTEG:" $itg1 $itg2
sp2_rano140203 ${prefix}.fits $ch ${prefix}.fits $itg1 $itg2
#       080931 -> 140203

do_linearity                # non-linearity補正
# mv ${prefix}.fits ${prefix}_intg.fits
# exit;

# do_dark_subtract          # ダーク差引
do_diff   $prefix           # 画像微分 兼 パラメータ取得
do_flat                     # フラット処理
do_kando_hosei              # 感度補正

##########
cp ${prefix}.fits output/.
if [ -f output/${prefix}.fits ]; then
    cp input/${prefix}.fits .
fi
##########

# do_1row_cray              # 1行モードでのcosmicrayの抜き出し(凍結)
do_sext_scon66 $prefix $ch  # Source extract をして seconds confirm を行う
# do_daophot                  # Daophot

##sp2_addrano080930 ${prefix}_mix.fits ${prefix}_mix.fits

do_wcs                      # FITS、events にWCSをつける

#温度依存性除去
detectortemp=6.5 #保険
case "$ch" in
    L)
	detectortemp=$(q_head ${prefix}_mixw.fits Ltp1)
	;;
    S)
	detectortemp=$(q_head ${prefix}_mixw.fits Stp1)
	;;
esac
if [ $detectortemp = "0.00" ];then
    echo -n "";
else
    sp2_tempcorr ${prefix}_mixw.fits $detectortemp ${prefix}_mixw.fits
fi

#黄道光除去
#あらかじめ計算しておいた短冊ごとの黄道光強度リストを参照
grep -q -s ${prefix} zod.dat
if [ $? = '0' ]
then
    #grepが成功した場合のみ黄道光除去
    grep -A 20 ${prefix} zod.dat|tail -n 20 > zoddata
    sp2_remzod ${prefix}_mixw.fits zoddata ${prefix}_mixw_remzod.fits
#else
#    echo 'zodiacal light is not subtracted...'
fi

### 片付け ###########################################################
# rep.datに記録する内容
echo "$ch $datestr $timestr $fid $ccsdsti $dhuti $cra $cde $rst1 $nrst1 $rst2 $nrst2 $msk1 $nmsk1 $msk2 $nmsk2 $bg1 $nbg1 $bg2 $nbg2 $nsrc $nrej1 $nrej2 $n_msx $n_iras $n_tmass $xshift $yshift $calc" > ${prefix}.rep;
# echo "done";

# rep2.datに記録する内容
echo "$ch $ccsdsti $bgA $nbgA $bgB $nbgB $bgC $nbgC $c1 $c2 $c3 $craA $cdeA $craB $cdeB $craC $cdeC $itg1 $nitg1 $itg2 $nitg2" > ${prefix}.rep2

# Gap情報をまとめ、1つのtextとfitsにする
# sp2_pkmsk.sh ${prefix} ${dhuti};
# sp2_ev_align.pl ${prefix}_scon.cat ${prefix}_mix.cat ${prefix}_mix.mag 2> /dev/null

# Mask情報の統合とmask FITSの作成
#sp2_mskmix.pl ${prefix}_slitm.dat ${prefix}_satur.dat ${prefix}_cray.dat > ${prefix}_msk.dat
sp2_mskmix.pl ${prefix}_slitm.dat ${prefix}_satur.dat > ${prefix}_msk.dat
# Swarp用weightイメージ
sp2_msk_t2b ${prefix}_msk.dat ${prefix}_mixw.fits.msk
q_arith ${prefix}_mixw.fits.msk x craymsk.fits msked.fits
mv msked.fits ${prefix}_mixw.fits.msk

weight_to_nscan ${prefix}_mixw.fits ${prefix}_mixw.fits.msk ${prefix}_mixw_nscan.fits

# 登録
#db_repreg.pl ${prefix}.rep
#db_evtreg.pl ${prefix}_scon.cat

##../db_gapreg.pl ${prefix}_mask.dat $ch
##../db_rejreg.pl ${prefix}_sconrej1.cat
##../db_rejreg.pl ${prefix}_sconrej2.cat
##../pack2.pl  ${prefix}
##../db_rep2db.pl ${prefix}_rep.txt
## db_reg_mix.pl ${prefix}_mixw.fits

# rep保存
if [ -f ${ch}rep.dat ]; then
    catcat.pl ${prefix}.rep >> ${ch}rep.dat  # Headerなし
else
    cat       ${prefix}.rep >  ${ch}rep.dat  # Header込み
fi

# rep2保存
if [ -f ${ch}rep2.dat ]; then
    catcat.pl ${prefix}.rep2 >> ${ch}rep2.dat  # Headerなし                     
else
    cat       ${prefix}.rep2 >  ${ch}rep2.dat  # Header込み                     
fi

# scon保存
if [ -f ${ch}scon.dat ]; then
    catcat.pl ${prefix}_scon.cat >> ${ch}scon.dat  # Headerなし
else
    cat       ${prefix}_scon.cat >  ${ch}scon.dat  # Header込み
fi

# 変数の保存
do_save_vals;
debug_stdout

# 残すもの 20121218
#sp2_nokosu.pl ${prefix}.fits ${prefix}_mixw.fits ${prefix}_mixw.fits.msk ${prefix}_scon.cat ${prefix}_moon.fits
# PR用

# SAA
#saa_hosei ${prefix}_mixw.fits ${prefix}_mixw.fits $nrej1 $nrej2 $ch

# MOON
#/home/ircscan/jisso_moon/remove_moon_program/sp2_mcorr.pl ${prefix}_mixw.fits

# sp2_nokosu.pl ${prefix}_mixw.fits ${prefix}_mixw_remzod.fits ${prefix}_mixw_nscan.fits ${prefix}_scon.cat ${prefix}_mixw.fits.msk ${prefix}_moon.fits ${prefix}_remscat.log 
sp2_nokosu.pl ${prefix}_mixw.fits ${prefix}_mixw_remzod.fits ${prefix}_mixw_nscan.fits ${prefix}_scon.cat ${prefix}_mixw.fits.msk ${prefix}_moon.fits ${prefix}_remscat.log ${prefix}.fits ${prefix}_intg.fits
#sp2_nokosu.pl ${prefix}_mixw.fits ${prefix}_scon.cat ${prefix}_mixw.fits.msk ${prefix}.pos ${prefix}_mix.fits ${prefix}.out ${prefix}.rep ${prefix}.rep2 ${prefix}_bg.fits
#sp2_nokosu.pl ${prefix}_scon.cat

exit 0;

